packages:
  - "apps/*"
  - "packages/*"

nodeLinker: hoisted

onlyBuiltDependencies:
  - "@prisma/engines"
  - "prisma"
  - "sharp"
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': true
  prisma: true
  sharp: true
